### ISSUE TITLE
HANG: Measuring a Process with CLR and IMetaDataDispenser hangs at shutdown

### ISSUE THREAD

**Issue by weidingerhp** [DynamoRIO/drmemory#1834]
DrMemory causes applications to hang during shutdown as soon as you open an IID_IMetaDataDispenser Interface and try to Load an assembly via "OpenScopeInMemory".

Reproducer can be found in:
https://github.com/weidingerhp/drmemoryclrreproducer

The Application runs fine until it should quit - then it stalls and can only be killed by taskmanager. (<ctrl>-C would quit DrMemory and send the other app into the background)

this does not happen if you use the "-handle_leaks_only" - switch (which brings far less data)

**Comment by derekbruening** [comment]
Please diagnose further:

1) Try the latest build from http://build.chromium.org/p/client.drmemory/builds/ as this may be a recently fixed bug.

2) Try disabling leaks via `-no_count_leaks`.  The leak scan is done at shutdown.

3) Try a debug build via `-debug` to see if any assertions trigger.

**Comment by weidingerhp** [comment]
ok ... will try this.
Thanks for the fast reply ...

**Comment by weidingerhp** [comment]
Tried again.

Following Results:
Starting without switches does not change the behavior. The Process still hangs @shutdown.
The "-no_count_leaks" lets the process terminate and the results are shown - would also be a workaround.

No debug assertions were noticed.

br
Hans-Peter

**Comment by derekbruening** [comment]
Is it possible that instead of a hang it's just really slow?  Attaching a debugger and looking at the callstacks (ideally then continuing and re-suspending) should give a clearer idea of whether it's making progress (or, look at whether it's taking up CPU at all).  We recently fixed a performance issue with the leak scan for apps that leave a lot of reachable memory around (#1852).  Perhaps it's better in the latest build https://build.chromium.org/p/client.drmemory/builds/DrMemory-Windows-1.9.16832-0x459f7f5-sfx.exe

**Comment by weidingerhp** [comment]
Issue is open for a long time. will close this.
Workaround did its job.
