### ISSUE TITLE
ERROR: failed to create process (err=2)

### ISSUE THREAD

**Issue by alex0419** [DynamoRIO/drmemory#1932]
Hi,
my operating system is Ubuntu 16.10. and i use DynamoRIO-Linux-6.1.1-3
i'm trying to run one of parsec 3.0 workload (canneal) with drmemory and get the following error:
ERROR: failed to create process (err=2) for "/home/alex/Desktop/parsec_3_0/bin/parsecmgmt":

The workload canneal is executed with the command " $ parsecmgmt -a run -p canneal "  in which parsecmgmt is a shell script

Step to reproduce the problem
1- download Parsec 3.0 and build canneal (" $ parsecmgmt -a build -p canneal ")
2- run canneal with drmemory ( $ PATH_TO_drmemory/drmemory -- parsecmgmt -a run -p canneal )

The problem does not go away when i run in light mode
same error running with DrMemory-Linux-1.9.16845-0xaa49f1a
when i pass " -debug -dr_debug -pause_at_assert"  there is no new message

**Comment by derekbruening** [comment]
Unfortunately the current injector does not properly handle directly
executing a #! script file and thus the docs say:

http://drmemory.org/docs/page_running.html#sec_invocation
"When running scripts it is best to explicitly invoke the interpreter
rather than invoking the script directly"

The next version will have support for direct invocation of #! scripts
(xref https://github.com/DynamoRIO/dynamorio/issues/2091).

**Comment by alex0419** [comment]
Thank you for the explanation
i was able to run it.
