### ISSUE TITLE
new drltrace test fails on android

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/drmemory#1972]
http://dynamorio.org/CDash/buildSummary.php?buildid=20451

```
*Tests failing*
drltrace (http://dynamorio.org/CDash/testDetails.php?test=226533&build=20451)
```

```
/work/drmemory/nightly/run/build_drmemory-android-dbg-32/bin/drltrace: /work/drmemory/nightly/run/build_drmemory-android-dbg-32/bin/drltrace: cannot execute binary file
```

It's not using adb shell.  It needs to be adjusted to copy the binary over and run over adb, or temporarily disabled for android.

**Comment by mxmssh** [comment]
It looks like we don't copy drltrace and drltracelib to our test device. I compiled DrMemory for Android manually with DRM_COPY_TO_DEVICE option and run tests. I didn't find any drltrace's files on my attached device while others were succesfully copied and then executed during the testing. 
Need further investigation.

**Comment by derekbruening** [comment]
In some cases you have to add the copy and the adb shell adjustment explicitly: see how the other android-enabled targets and tests are doing it.

**Comment by mxmssh** [comment]
Ok, the first problem solved. The test is running, files exist. However, since I don't have LD_LIBRARY_PATH env. variable, drltrace now raises the following error:
CANNOT LINK EXECUTABLE: library "libdynamorio.so" not found ...

Do we have such problem on CDash ? What about actual users ? Do they need to specify LD_LIBRARY_PATH to be able to run drltrace ?

**Comment by mxmssh** [comment]
We have a comment for unit_tests 
/data/local/tmp/build_android/bin/unit_tests Make sure the loader finds the dynamorio library (set LD_LIBRARY_PATH)
So, probably the same we need for drltrace...
