### ISSUE TITLE
Is drmemory patch code missing a needed CLD on x86 architecture?

### ISSUE THREAD

**Issue by d-hoke** [DynamoRIO/drmemory#2092]
proprietary application, visstudio cpp x64, windows 10 home

For a bit more detail, see https://github.com/DynamoRIO/drmemory/issues/2091 description, as it contains another problem hunt that encountered this possible secondary issue.  The CLD encounter is noted close to the bottom of that hunt description.

It appears that a CLD might be prudent in dynamorio\core\arch\x86\x86_asm_defines.asm  in the REP_STRING_OP macro, or in other code that uses it (if something actually needs to be able to operate in reverse direction).  I was unable to quickly determine whether something elsewhere in the full code path may have performed that so that the direction flag at that point in code would be 'increasing' as the code seems to expect.  I was also not completely certain, but it did appear that an exception (which is being trapped) might have been occurring because of an incorrect direction of string operation (and thus the intended exception trapping around that code would not be obtaining correct results.)  

I did find a CLD in other code, but was not able to recognize a connection between the two, nor recognize with any certainty that there was no connection.

**Comment by derekbruening** [comment]
DF is cleared on all paths into DR system code (required by the ABI: otherwise compiler-generated code, and not just hand-written asm, would be forced to execute CLD all over the place), so it should not be needed in any code run from the DR dispatcher or indirectly from client clean call code.  I don't see enough evidence in #2091 about the direction being wrong: just your comment "backwards".  If you have more concrete evidence please supply it.

**Comment by derekbruening** [comment]
(DF is cleared using things like PUSH 0;POPF in the context switch code)
