### ISSUE TITLE
application exited with abnormal code0x28

### ISSUE THREAD

**Issue by Lorenzoqs** [DynamoRIO/drmemory#2494]
**Describe the bug**
Today,I use Dr memory on Windows10 visual studio2015 to detect leak.After run Dr memory,It shows that:Failed to take over all threads after multiple attempts
The version of the Dr memory is 2.6.0

**Comment by derekbruening** [comment]
There is nothing actionable here: no base information on what application was run, what happens on other applications, what happens with debug build.  There are many key questions in the bug template: it looks like the template was just deleted rather than answer the questions!  Going to have to close without the template info.
